name: Amazon Hot Wheels Monitor

on:
  schedule:
    - cron: '*/20 * * * *' # Every 20 mins (safer than 15 to avoid bans)
  workflow_dispatch: # Allows manual run

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial for saving the JSON file
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Deps
        run: pip install requests beautifulsoup4

      - name: Run Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python monitor.py

      - name: Save State
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add latest_seen.json
          git commit -m "Update seen items [skip ci]" || exit 0
          git push
